id: PD041453E
initial_creation_type: ocr
source_metadata:
  volumes:
    241674a533164d90b4c01c682fb1a0bc:
      base_file: v037.txt
      image_group_id: I1PD95882
      title: ཡན་ལག་བདུན་པའི་སྒྲུབ་ཐབས།
      total_pages: 1379
      volume_number: 37
